spring.application.name=product-service

server.port=8081

spring.datasource.url=jdbc:postgresql://dpg-d8459vcvikkc738s8j1g-a.oregon-postgres.render.com/ccom_db
spring.datasource.username=yusuf
spring.datasource.password=smW9iGkuQvM95AA4hcXQXZ4SZsRLMwA6

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect